#!/usr/bin/env python3
"""Maintainer-only generator for CPython unicodedata \\N{name} tables.

Includes every unicodedata.name entry plus Unicode NameAliases accepted by
unicodedata.lookup. Go tests/builds/production never invoke this script.

Example:

  python3 \\
    conformance/compat/format_selector/generate_unicode_names.py --write
"""

from __future__ import annotations

import argparse
import hashlib
import platform
import struct
import sys
import unicodedata
import urllib.request
import zlib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
NAME_ALIASES_URL = "https://www.unicode.org/Public/15.0.0/ucd/NameAliases.txt"
NAME_ALIASES_SHA256 = "3e39509e8fae3e5d50ba73759d0b97194501d14a9c63107a6372a46b38be18e8"
PINNED_PYTHON_VERSION = "3.12.13"
PINNED_UNICODE_VERSION = "15.0.0"


def load_name_aliases(path: Path | None) -> dict[str, int]:
    if path is None:
        data = urllib.request.urlopen(NAME_ALIASES_URL, timeout=60).read()
    else:
        data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != NAME_ALIASES_SHA256:
        raise SystemExit(
            f"NameAliases.txt sha256 {digest} != pinned {NAME_ALIASES_SHA256}"
        )
    aliases: dict[str, int] = {}
    for line in data.decode("utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        parts = [part.strip() for part in line.split(";")]
        if len(parts) < 2:
            continue
        aliases[parts[1]] = int(parts[0], 16)
    return aliases


def build_entries(alias_path: Path | None) -> tuple[dict[str, int], str]:
    entries: dict[str, int] = {}
    for cp in range(0x110000):
        try:
            name = unicodedata.name(chr(cp))
        except ValueError:
            continue
        entries[name] = cp
    for name, cp in load_name_aliases(alias_path).items():
        entries.setdefault(name, cp)
    return entries, unicodedata.unidata_version


def build_payload(entries: dict[str, int]) -> bytes:
    buf = bytearray()
    for name, cp in sorted(entries.items()):
        encoded = name.encode("utf-8")
        if len(encoded) > 65535:
            raise SystemExit(f"name too long: {name}")
        buf += struct.pack(">IH", cp, len(encoded))
        buf += encoded
    return zlib.compress(bytes(buf), 9)


def render_go(count: int, unidata: str, blob_sha: str, blob_bytes: int) -> str:
    return f"""// Code generated by conformance/compat/format_selector/generate_unicode_names.py. DO NOT EDIT.
// Source: CPython {platform.python_version()} unicodedata {unidata}
// Entries: {count} (canonical names + NameAliases.txt)
// NameAliases.txt: Unicode 15.0.0 sha256={NAME_ALIASES_SHA256}
// Artifact: unicode_names.bin zlib payload sha256={blob_sha} bytes={blob_bytes}

package format

import (
	"bytes"
	"compress/zlib"
	_ "embed"
	"encoding/binary"
	"io"
	"strings"
	"sync"
)

//go:embed unicode_names.bin
var pythonUnicodeNameBlob []byte

const pythonUnicodeDataVersion = "{unidata}"

var (
	pythonUnicodeNameOnce sync.Once
	pythonUnicodeNameMap  map[string]rune
)

func lookupPythonUnicodeName(name string) (rune, bool) {{
	pythonUnicodeNameOnce.Do(loadPythonUnicodeNames)
	r, ok := pythonUnicodeNameMap[strings.ToUpper(name)]
	return r, ok
}}

func loadPythonUnicodeNames() {{
	pythonUnicodeNameMap = make(map[string]rune, {count})
	raw, err := zlib.NewReader(bytes.NewReader(pythonUnicodeNameBlob))
	if err != nil {{
		panic("format: unicode name table: " + err.Error())
	}}
	defer raw.Close()
	data, err := io.ReadAll(raw)
	if err != nil {{
		panic("format: unicode name table: " + err.Error())
	}}
	for offset := 0; offset < len(data); {{
		if offset+6 > len(data) {{
			panic("format: unicode name table truncated")
		}}
		cp := binary.BigEndian.Uint32(data[offset : offset+4])
		n := int(binary.BigEndian.Uint16(data[offset+4 : offset+6]))
		offset += 6
		if offset+n > len(data) {{
			panic("format: unicode name table truncated name")
		}}
		pythonUnicodeNameMap[string(data[offset:offset+n])] = rune(cp)
		offset += n
	}}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument(
        "--aliases",
        type=Path,
        help="Local Unicode NameAliases.txt (default: download 15.0.0)",
    )
    args = parser.parse_args()
    if platform.python_version() != PINNED_PYTHON_VERSION:
        print(
            f"CPython {PINNED_PYTHON_VERSION} required; got {platform.python_version()}",
            file=sys.stderr,
        )
        return 2
    if unicodedata.unidata_version != PINNED_UNICODE_VERSION:
        print(
            f"Unicode {PINNED_UNICODE_VERSION} required; got {unicodedata.unidata_version}",
            file=sys.stderr,
        )
        return 2
    entries, unidata = build_entries(args.aliases)
    payload = build_payload(entries)
    blob_sha = hashlib.sha256(payload).hexdigest()
    go_text = render_go(len(entries), unidata, blob_sha, len(payload))
    bin_out = REPO_ROOT / "internal" / "format" / "unicode_names.bin"
    go_out = REPO_ROOT / "internal" / "format" / "unicode_names.go"
    if args.write:
        bin_out.write_bytes(payload)
        go_out.write_text(go_text, encoding="utf-8")
        old = REPO_ROOT / "internal" / "format" / "unicode_names_gen.go"
        if old.exists():
            old.unlink()
    print(
        f"names={len(entries)} unidata={unidata} zlib_bytes={len(payload)} "
        f"sha256={blob_sha} wrote={args.write} bin={bin_out} go={go_out}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
