// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeURL(arg1) {
  return window['go']['main']['App']['AnalyzeURL'](arg1);
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function ClearCompletedJobs() {
  return window['go']['main']['App']['ClearCompletedJobs']();
}

export function ClearDownloads() {
  return window['go']['main']['App']['ClearDownloads']();
}

export function ClearFFmpegPath() {
  return window['go']['main']['App']['ClearFFmpegPath']();
}

export function ConfigureFFmpeg(arg1) {
  return window['go']['main']['App']['ConfigureFFmpeg'](arg1);
}

export function CopyDiagnostics() {
  return window['go']['main']['App']['CopyDiagnostics']();
}

export function GetFFmpegStatus() {
  return window['go']['main']['App']['GetFFmpegStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListDownloads() {
  return window['go']['main']['App']['ListDownloads']();
}

export function ListJobs() {
  return window['go']['main']['App']['ListJobs']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PickDownloadFolder() {
  return window['go']['main']['App']['PickDownloadFolder']();
}

export function PickFFmpegPath() {
  return window['go']['main']['App']['PickFFmpegPath']();
}

export function ProbeFFmpeg() {
  return window['go']['main']['App']['ProbeFFmpeg']();
}

export function RemoveDownload(arg1) {
  return window['go']['main']['App']['RemoveDownload'](arg1);
}

export function RemoveJob(arg1) {
  return window['go']['main']['App']['RemoveJob'](arg1);
}

export function RetryJob(arg1) {
  return window['go']['main']['App']['RetryJob'](arg1);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function ValidateURL(arg1) {
  return window['go']['main']['App']['ValidateURL'](arg1);
}
