// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jobs} from '../models';
import {ffmpegdetect} from '../models';
import {store} from '../models';
import {urlcheck} from '../models';

export function AnalyzeURL(arg1:string):Promise<jobs.InfoSummary>;

export function CancelJob(arg1:string):Promise<void>;

export function ClearCompletedJobs():Promise<void>;

export function ClearDownloads():Promise<void>;

export function ClearFFmpegPath():Promise<ffmpegdetect.Status>;

export function ConfigureFFmpeg(arg1:string):Promise<ffmpegdetect.Status>;

export function CopyDiagnostics():Promise<string>;

export function GetFFmpegStatus():Promise<ffmpegdetect.Status>;

export function GetSettings():Promise<store.Settings>;

export function ListDownloads():Promise<Array<store.HistoryEntry>>;

export function ListJobs():Promise<Array<jobs.JobSnapshot>>;

export function OpenFile(arg1:string):Promise<void>;

export function PickDownloadFolder():Promise<string>;

export function PickFFmpegPath():Promise<string>;

export function ProbeFFmpeg():Promise<ffmpegdetect.Status>;

export function RemoveDownload(arg1:string):Promise<void>;

export function RemoveJob(arg1:string):Promise<void>;

export function RetryJob(arg1:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;

export function StartDownload(arg1:jobs.Request):Promise<string>;

export function UpdateSettings(arg1:store.Settings):Promise<store.Settings>;

export function ValidateURL(arg1:string):Promise<urlcheck.Result>;
