package release

import (
	"archive/tar"
	"archive/zip"
	"bytes"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/rand"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

var releaseEpoch = time.Date(2026, 7, 18, 12, 0, 0, 0, time.UTC)

func TestBuildPlanIsExplicitAndDeterministic(t *testing.T) {
	options := BuildOptions{Target: Target{GOOS: "linux", GOARCH: "amd64"}, MainPackage: "./cmd/ytdlp-go", Output: "ytdlp-go", SourceDateEpoch: releaseEpoch, Tags: []string{"osusergo", "netgo"}}
	first, err := NewBuildPlan(options)
	if err != nil {
		t.Fatal(err)
	}
	second, err := NewBuildPlan(options)
	if err != nil {
		t.Fatal(err)
	}
	firstJSON, _ := json.Marshal(first)
	secondJSON, _ := json.Marshal(second)
	if !bytes.Equal(firstJSON, secondJSON) {
		t.Fatal("build plans differ")
	}
	if first.Program != "go" || strings.Join(first.Environment, " ") != "CGO_ENABLED=0 GOARCH=amd64 GOOS=linux SOURCE_DATE_EPOCH=1784376000" || !contains(first.Arguments, "-trimpath") || !contains(first.Arguments, "-buildvcs=false") || !contains(first.Arguments, "-ldflags=-buildid=") || !contains(first.Arguments, "-tags=netgo,osusergo") {
		t.Fatalf("plan = %#v", first)
	}
	options.MainPackage = "./cmd/ytdlp-go;curl"
	if _, err := NewBuildPlan(options); !errors.Is(err, ErrInvalidInput) {
		t.Fatalf("unsafe package error = %v", err)
	}
}

func TestReleaseConformanceFixtures(t *testing.T) {
	artifacts := map[string][]byte{"b.zip": []byte("b"), "a.tar.gz": []byte("a")}
	var generated bytes.Buffer
	if err := WriteChecksums(&generated, artifacts); err != nil {
		t.Fatal(err)
	}
	expected, err := os.ReadFile(filepath.Join("..", "..", "conformance", "release", "checksums.expected.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(generated.Bytes(), expected) {
		t.Fatalf("checksum fixture drift:\n%s", generated.Bytes())
	}
	encodedPlan, err := os.ReadFile(filepath.Join("..", "..", "conformance", "release", "build-plan.expected.json"))
	if err != nil {
		t.Fatal(err)
	}
	var expectedPlan struct {
		Target      Target   `json:"target"`
		Program     string   `json:"program"`
		Arguments   []string `json:"arguments"`
		Environment []string `json:"environment"`
	}
	if err := json.Unmarshal(encodedPlan, &expectedPlan); err != nil {
		t.Fatal(err)
	}
	plan, err := NewBuildPlan(BuildOptions{Target: expectedPlan.Target, MainPackage: "./cmd/ytdlp-go", Output: "ytdlp-go", SourceDateEpoch: releaseEpoch, Tags: []string{"osusergo", "netgo"}})
	if err != nil {
		t.Fatal(err)
	}
	if plan.Program != expectedPlan.Program || strings.Join(plan.Arguments, "\x00") != strings.Join(expectedPlan.Arguments, "\x00") || strings.Join(plan.Environment, "\x00") != strings.Join(expectedPlan.Environment, "\x00") {
		t.Fatalf("build plan fixture drift: %#v", plan)
	}
}

func TestArchivesAreReproducibleAndNormalized(t *testing.T) {
	entries := []Entry{
		{Name: "ytdlp-go/LICENSES.txt", Data: []byte("license\n")},
		{Name: "ytdlp-go/ytdlp-go", Data: []byte("binary"), Executable: true},
	}
	for _, format := range []ArchiveFormat{FormatTarGzip, FormatZIP} {
		t.Run(string(format), func(t *testing.T) {
			build := func(_ context.Context, writer io.Writer) error {
				return WriteArchive(context.Background(), writer, format, entries, releaseEpoch)
			}
			digest, err := CheckReproducible(context.Background(), build, 1<<20)
			if err != nil || !validDigest(digest) {
				t.Fatalf("digest=%q err=%v", digest, err)
			}
			var encoded bytes.Buffer
			if err := build(context.Background(), &encoded); err != nil {
				t.Fatal(err)
			}
			if format == FormatTarGzip {
				assertTar(t, encoded.Bytes())
			} else {
				assertZIP(t, encoded.Bytes())
			}
		})
	}
}

func assertTar(t *testing.T, encoded []byte) {
	t.Helper()
	gzipReader, err := gzip.NewReader(bytes.NewReader(encoded))
	if err != nil {
		t.Fatal(err)
	}
	if !gzipReader.Header.ModTime.Equal(releaseEpoch) || gzipReader.Header.Name != "" {
		t.Fatalf("gzip header = %#v", gzipReader.Header)
	}
	tarReader := tar.NewReader(gzipReader)
	var names []string
	for {
		header, err := tarReader.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			t.Fatal(err)
		}
		names = append(names, header.Name)
		if !header.ModTime.Equal(releaseEpoch) || header.Uid != 0 || header.Gid != 0 {
			t.Fatalf("tar header = %#v", header)
		}
	}
	if strings.Join(names, ",") != "ytdlp-go/LICENSES.txt,ytdlp-go/ytdlp-go" {
		t.Fatalf("tar order = %v", names)
	}
}

func assertZIP(t *testing.T, encoded []byte) {
	t.Helper()
	reader, err := zip.NewReader(bytes.NewReader(encoded), int64(len(encoded)))
	if err != nil {
		t.Fatal(err)
	}
	if len(reader.File) != 2 || reader.File[0].Name != "ytdlp-go/LICENSES.txt" || reader.File[1].Name != "ytdlp-go/ytdlp-go" {
		t.Fatalf("zip files = %#v", reader.File)
	}
	for _, file := range reader.File {
		if !file.Modified.Equal(releaseEpoch) {
			t.Fatalf("zip time = %v", file.Modified)
		}
	}
	if reader.File[1].Mode().Perm() != 0o755 {
		t.Fatalf("executable mode = %v", reader.File[1].Mode())
	}
}

func TestArchiveOrderPropertyAndHostilePaths(t *testing.T) {
	original := []Entry{{Name: "root/c", Data: []byte("c")}, {Name: "root/a", Data: []byte("a")}, {Name: "root/b", Data: []byte("b")}}
	var baseline bytes.Buffer
	if err := WriteArchive(context.Background(), &baseline, FormatTarGzip, original, releaseEpoch); err != nil {
		t.Fatal(err)
	}
	for seed := int64(0); seed < 20; seed++ {
		permuted := append([]Entry(nil), original...)
		rand.New(rand.NewSource(seed)).Shuffle(len(permuted), func(i, j int) { permuted[i], permuted[j] = permuted[j], permuted[i] })
		var output bytes.Buffer
		if err := WriteArchive(context.Background(), &output, FormatTarGzip, permuted, releaseEpoch); err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(output.Bytes(), baseline.Bytes()) {
			t.Fatalf("seed %d changed archive", seed)
		}
	}
	for _, name := range []string{"../escape", "/absolute", `root\\escape`, "root/../escape", "root/name.", "root//name", "root/CON"} {
		if err := WriteArchive(context.Background(), io.Discard, FormatZIP, []Entry{{Name: name}}, releaseEpoch); !errors.Is(err, ErrUnsafePath) {
			t.Errorf("path %q error = %v", name, err)
		}
	}
	if err := WriteArchive(context.Background(), io.Discard, FormatZIP, []Entry{{Name: "Root/File"}, {Name: "root/file"}}, releaseEpoch); !errors.Is(err, ErrUnsafePath) {
		t.Fatalf("case collision error = %v", err)
	}
}

func TestChecksumsLicensesSBOMAndManifest(t *testing.T) {
	artifacts := map[string][]byte{"b.zip": []byte("b"), "a.tar.gz": []byte("a")}
	var checksums bytes.Buffer
	if err := WriteChecksums(&checksums, artifacts); err != nil {
		t.Fatal(err)
	}
	if !strings.HasSuffix(checksums.String(), "  b.zip\n") || strings.Index(checksums.String(), "a.tar.gz") > strings.Index(checksums.String(), "b.zip") {
		t.Fatalf("checksums = %q", checksums.String())
	}
	if err := VerifyChecksums(checksums.Bytes(), artifacts); err != nil {
		t.Fatal(err)
	}
	tampered := bytes.Replace(checksums.Bytes(), []byte("a.tar.gz"), []byte("x.tar.gz"), 1)
	if err := VerifyChecksums(tampered, artifacts); !errors.Is(err, ErrInvalidInput) {
		t.Fatalf("tampered checksums error = %v", err)
	}

	licenses := []License{
		{Component: "module-b", Version: "v2.0.0", SPDX: "Apache-2.0", Text: []byte("B license\r\n")},
		{Component: "module-a", Version: "v1.0.0", SPDX: "MIT", Text: []byte("A license\n")},
	}
	var bundle bytes.Buffer
	if err := WriteLicenseBundle(&bundle, licenses); err != nil {
		t.Fatal(err)
	}
	if bundle.String() != "===== module-a v1.0.0 (MIT) =====\nA license\n\n===== module-b v2.0.0 (Apache-2.0) =====\nB license\n\n" {
		t.Fatalf("license bundle = %q", bundle.String())
	}

	componentDigest := sha256.Sum256([]byte("component"))
	components := []Component{
		{Name: "module-b", Version: "v2.0.0", SPDXID: "SPDXRef-Package-module-b", LicenseDeclared: "Apache-2.0", Download: "https://example.invalid/module-b", SHA256: fmt.Sprintf("%x", componentDigest)},
		{Name: "module-a", Version: "v1.0.0", SPDXID: "SPDXRef-Package-module-a", LicenseDeclared: "MIT", Download: "NOASSERTION"},
	}
	if err := ValidateLicenseCoverage(components, licenses); err != nil {
		t.Fatal(err)
	}
	if err := ValidateLicenseCoverage(components, licenses[:1]); !errors.Is(err, ErrInvalidInput) {
		t.Fatalf("missing license error = %v", err)
	}
	var sbom bytes.Buffer
	if err := WriteSPDX(&sbom, SBOMOptions{Name: "ytdlp-go-1.0.0", Namespace: "https://ytdlp-go.invalid/sbom/1.0.0", Created: releaseEpoch, Creator: "Tool: ytdlp-go-release", Components: components}); err != nil {
		t.Fatal(err)
	}
	components[0].Download = "https://token:secret@example.invalid/module"
	if err := WriteSPDX(io.Discard, SBOMOptions{Name: "ytdlp-go-1.0.0", Namespace: "https://ytdlp-go.invalid/sbom/1.0.0", Created: releaseEpoch, Creator: "Tool: ytdlp-go-release", Components: components}); !errors.Is(err, ErrInvalidInput) || strings.Contains(fmt.Sprint(err), "secret") {
		t.Fatalf("credential URL error = %v", err)
	}
	if !bytes.Contains(sbom.Bytes(), []byte(`"spdxVersion":"SPDX-2.3"`)) || bytes.Index(sbom.Bytes(), []byte("module-a")) > bytes.Index(sbom.Bytes(), []byte("module-b")) {
		t.Fatalf("SBOM = %s", sbom.Bytes())
	}

	contents := map[string]struct {
		Target Target
		Data   []byte
	}{
		"ytdlp-go_linux_amd64.tar.gz": {Target: Target{GOOS: "linux", GOARCH: "amd64"}, Data: []byte("linux")},
		"ytdlp-go_windows_amd64.zip":  {Target: Target{GOOS: "windows", GOARCH: "amd64"}, Data: []byte("windows")},
	}
	manifest, err := NewManifest("v1.0.0-alpha.1", "aefce1eea4d0b6bab1ec2bd3beff09bff91a39c8", releaseEpoch, contents)
	if err != nil {
		t.Fatal(err)
	}
	var encodedManifest bytes.Buffer
	if err := WriteManifest(&encodedManifest, manifest); err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(encodedManifest.Bytes(), []byte(`"schema":"ytdlp-go-release-v1"`)) {
		t.Fatalf("manifest = %s", encodedManifest.Bytes())
	}
}

func TestCheckReproducibleFailures(t *testing.T) {
	counter := 0
	_, err := CheckReproducible(context.Background(), func(_ context.Context, writer io.Writer) error {
		counter++
		_, err := fmt.Fprint(writer, counter)
		return err
	}, 10)
	if !errors.Is(err, ErrNotReproducible) {
		t.Fatalf("difference error = %v", err)
	}
	_, err = CheckReproducible(context.Background(), func(_ context.Context, writer io.Writer) error {
		_, err := writer.Write(make([]byte, 11))
		return err
	}, 10)
	if !errors.Is(err, ErrTooLarge) {
		t.Fatalf("limit error = %v", err)
	}
}

func contains(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}

func FuzzArchivePaths(f *testing.F) {
	f.Add("root/ytdlp-go")
	f.Add("../escape")
	f.Add("CON")
	f.Fuzz(func(t *testing.T, name string) {
		_ = WriteArchive(context.Background(), io.Discard, FormatZIP, []Entry{{Name: name, Data: []byte("x")}}, releaseEpoch)
	})
}

func FuzzChecksumManifest(f *testing.F) {
	f.Add([]byte("bad\n"))
	f.Add([]byte("00  file\n"))
	f.Fuzz(func(t *testing.T, encoded []byte) {
		_ = VerifyChecksums(encoded, map[string][]byte{"file": []byte("x")})
	})
}
