// Package netscape reads and writes Netscape/Mozilla cookies.txt files.
package netscape

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"
)

const (
	maxLineBytes = 1 << 20
	maxCookies   = 1_000_000
)

var (
	ErrMalformed   = errors.New("malformed Netscape cookie file")
	ErrWrongFormat = errors.New("cookie file is not Netscape format")
	ErrTooLarge    = errors.New("Netscape cookie file exceeds safety limits")
	ErrFile        = errors.New("cannot open Netscape cookie file")
)

// Entry retains the host-only bit that net/http.Cookie cannot represent.
type Entry struct {
	Cookie            *http.Cookie
	IncludeSubdomains bool
}

type Result struct {
	Entries  []Entry
	Total    int
	Imported int
	Skipped  int
	Session  int
	Expired  int
}

type Options struct {
	// IncludeExpired retains expired persistent cookies. It defaults to true,
	// matching yt-dlp's cookie-file loading behavior.
	DropExpired bool
	Now         time.Time
}

func LoadFile(ctx context.Context, path string, options Options) (Result, error) {
	file, err := os.Open(path)
	if err != nil {
		return Result{}, fmt.Errorf("%w: %w", ErrFile, err)
	}
	defer file.Close()
	result, err := Parse(ctx, file, options)
	if err == nil || errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) ||
		errors.Is(err, ErrMalformed) || errors.Is(err, ErrWrongFormat) || errors.Is(err, ErrTooLarge) {
		return result, err
	}
	return result, fmt.Errorf("%w: %w", ErrFile, err)
}

// Parse accepts valid lines and reports malformed lines as a categorized
// partial-result error. Error text never includes cookie names or values.
func Parse(ctx context.Context, input io.Reader, options Options) (Result, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	now := options.Now
	if now.IsZero() {
		now = time.Now()
	}
	scanner := bufio.NewScanner(input)
	scanner.Buffer(make([]byte, 4096), maxLineBytes)
	var result Result
	malformed := 0
	for scanner.Scan() {
		if err := ctx.Err(); err != nil {
			return result, err
		}
		line := strings.TrimSuffix(scanner.Text(), "\r")
		httpOnly := false
		if strings.HasPrefix(line, "#HttpOnly_") {
			httpOnly = true
			line = strings.TrimPrefix(line, "#HttpOnly_")
		} else if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}
		result.Total++
		if result.Total > maxCookies {
			return result, ErrTooLarge
		}
		fields := strings.Split(line, "\t")
		if len(fields) != 7 {
			if result.Total == 1 && looksLikeJSON(line) {
				return result, ErrWrongFormat
			}
			malformed++
			result.Skipped++
			continue
		}
		domain, include, path, secure, expiresRaw, name, value := fields[0], fields[1], fields[2], fields[3], fields[4], fields[5], fields[6]
		if !validDomain(domain) || path == "" || path[0] != '/' || invalidField(name) || invalidField(value) {
			malformed++
			result.Skipped++
			continue
		}
		includeSubdomains, ok := parseBool(include)
		if !ok {
			malformed++
			result.Skipped++
			continue
		}
		isSecure, ok := parseBool(secure)
		if !ok {
			malformed++
			result.Skipped++
			continue
		}
		cookie := &http.Cookie{Name: name, Value: value, Domain: domain, Path: path, Secure: isSecure, HttpOnly: httpOnly}
		if expiresRaw == "" || expiresRaw == "0" {
			result.Session++
		} else {
			expires, err := strconv.ParseFloat(expiresRaw, 64)
			if err != nil || expires < 0 {
				malformed++
				result.Skipped++
				continue
			}
			cookie.Expires = time.Unix(int64(expires), 0)
			if cookie.Expires.Before(now) {
				result.Expired++
				if options.DropExpired {
					result.Skipped++
					continue
				}
			}
		}
		result.Entries = append(result.Entries, Entry{Cookie: cookie, IncludeSubdomains: includeSubdomains})
		result.Imported++
	}
	if err := scanner.Err(); err != nil {
		if errors.Is(err, bufio.ErrTooLong) || strings.Contains(err.Error(), "token too long") {
			return result, ErrTooLarge
		}
		return result, fmt.Errorf("read Netscape cookie file: %w", err)
	}
	if malformed > 0 {
		return result, fmt.Errorf("%w: %d entries skipped", ErrMalformed, malformed)
	}
	return result, nil
}

func Write(ctx context.Context, output io.Writer, entries []Entry) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if _, err := io.WriteString(output, "# Netscape HTTP Cookie File\n# Generated by ytdlp-go. Do not edit.\n\n"); err != nil {
		return err
	}
	for _, entry := range entries {
		if err := ctx.Err(); err != nil {
			return err
		}
		cookie := entry.Cookie
		if cookie == nil || !validDomain(cookie.Domain) || cookie.Path == "" || cookie.Path[0] != '/' || invalidField(cookie.Name) || invalidField(cookie.Value) {
			return ErrMalformed
		}
		domain := cookie.Domain
		if cookie.HttpOnly {
			domain = "#HttpOnly_" + domain
		}
		expires := "0"
		if !cookie.Expires.IsZero() {
			expires = strconv.FormatInt(cookie.Expires.Unix(), 10)
		}
		fields := []string{domain, boolText(entry.IncludeSubdomains), cookie.Path, boolText(cookie.Secure), expires, cookie.Name, cookie.Value}
		if _, err := io.WriteString(output, strings.Join(fields, "\t")+"\n"); err != nil {
			return err
		}
	}
	return nil
}

func looksLikeJSON(line string) bool {
	trimmed := strings.TrimSpace(line)
	return strings.HasPrefix(trimmed, "{") || strings.HasPrefix(trimmed, "[")
}

func parseBool(value string) (bool, bool) {
	switch strings.ToUpper(value) {
	case "TRUE":
		return true, true
	case "FALSE":
		return false, true
	default:
		return false, false
	}
}

func boolText(value bool) string {
	if value {
		return "TRUE"
	}
	return "FALSE"
}

func validDomain(domain string) bool {
	if domain == "" || len(domain) > 255 || strings.ContainsAny(domain, "\t\r\n /\\") {
		return false
	}
	trimmed := strings.TrimPrefix(domain, ".")
	return trimmed != "" && !strings.HasPrefix(trimmed, ".") && !strings.HasSuffix(trimmed, ".")
}

func invalidField(value string) bool { return strings.ContainsAny(value, "\t\r\n\x00") }
