// Code generated by conformance/compat/format_selector/generate_unicode_names.py. DO NOT EDIT.
// Source: CPython 3.12.13 unicodedata 15.0.0
// Entries: 143514 (canonical names + NameAliases.txt)
// NameAliases.txt: Unicode 15.0.0 sha256=3e39509e8fae3e5d50ba73759d0b97194501d14a9c63107a6372a46b38be18e8
// Artifact: unicode_names.bin zlib payload sha256=0a76d5792d895a7054d63c8789f0fb79790b58608cbb0bc18426a236c84cf2de bytes=700996

package pyregex

import (
	"bytes"
	"compress/zlib"
	_ "embed"
	"encoding/binary"
	"io"
	"strings"
	"sync"
)

//go:embed unicode_names.bin
var pythonUnicodeNameBlob []byte

const pythonUnicodeDataVersion = "15.0.0"

var (
	pythonUnicodeNameOnce sync.Once
	pythonUnicodeNameMap  map[string]rune
)

func lookupPythonUnicodeName(name string) (rune, bool) {
	pythonUnicodeNameOnce.Do(loadPythonUnicodeNames)
	r, ok := pythonUnicodeNameMap[strings.ToUpper(name)]
	return r, ok
}

func loadPythonUnicodeNames() {
	pythonUnicodeNameMap = make(map[string]rune, 143514)
	raw, err := zlib.NewReader(bytes.NewReader(pythonUnicodeNameBlob))
	if err != nil {
		panic("format: unicode name table: " + err.Error())
	}
	defer raw.Close()
	data, err := io.ReadAll(raw)
	if err != nil {
		panic("format: unicode name table: " + err.Error())
	}
	for offset := 0; offset < len(data); {
		if offset+6 > len(data) {
			panic("format: unicode name table truncated")
		}
		cp := binary.BigEndian.Uint32(data[offset : offset+4])
		n := int(binary.BigEndian.Uint16(data[offset+4 : offset+6]))
		offset += 6
		if offset+n > len(data) {
			panic("format: unicode name table truncated name")
		}
		pythonUnicodeNameMap[string(data[offset:offset+n])] = rune(cp)
		offset += n
	}
}
